from __future__ import annotations

import re

import write_recap


HIGH_LOFT_EDITORIAL = r"""

HIGH LOFT EDITORIAL OVERRIDES
These rules are more specific than the generic recap rules above and control the final style.

CARNAGE COMMENTARY
- The renderer ALREADY shows the full shot trail immediately above the commentary. DO NOT narrate that trail back to the reader.
- Never walk through every shot in order. Never write a play-by-play recap such as "the drive went..., then..., then..., then...".
- Commentary should be 1-3 punchy sentences and normally 20-55 words.
- Pick only the one or two moments that define why the hole became ridiculous: a penalty, shank, bunker loop, zero/one-yard move, repeated failed recovery, four-putt, etc.
- If the trail itself is funny, summarize the pattern rather than restating distances. Example: "Three straight recovery attempts somehow made the hole less solved each time. By the time he found the green, the par four had become a hostage situation."
- The job is interpretation + joke. The visible shot trail is the evidence.

PLAYER-BY-PLAYER BODY
- Write a STORY about the round, not an inventory of the fact package.
- Start from a clear thesis: what kind of round was this, what actually drove the net result, and what does it say about this player's golf right now?
- Be selective. Use only the 2-4 most useful numbers/facts that explain the story. Do not march through SG categories, GIR, fairways, putts, birdies, doubles, and worst-hole details just because they exist.
- A stat earns its way into the paragraph only if it changes the reader's understanding of the round.
- Prefer synthesis: "the irons carried him while the putter tried to file an injunction" over a category-by-category data dump.
- Shot evidence is seasoning, not a transcript. Mention a specific hole/shot only when it is unusually funny, decisive, or revealing.
- Prior history should be used only when it adds a real comparison or trend. Do not mechanically append prior averages to every player.
- Do not end with a mini spreadsheet sentence containing several metrics.
- Aim for roughly 90-150 words, but prioritize a cohesive funny paragraph over filling space.

OVERALL
- Assume the reader can see the leaderboard, shot trail, and metric cards on the page. Copy should add judgment, synthesis, context, and comedy rather than duplicate visible information.
- If a sentence could be generated by simply reading numbers left-to-right from the fact package, rewrite or delete it.
""".strip()

write_recap.SYSTEM_PROMPT = write_recap.SYSTEM_PROMPT + "\n\n" + HIGH_LOFT_EDITORIAL

_original_validate = write_recap.validate_copy


def high_loft_validate(copy: dict, facts: dict) -> None:
    _original_validate(copy, facts)

    for item in copy.get("carnage", []):
        text = (item.get("commentary") or "").strip()
        words = re.findall(r"\b\w+[’'-]?\w*\b", text)
        if len(words) > 65:
            raise RuntimeError(
                f"Carnage commentary is too long / too play-by-play for {item.get('name')}: {len(words)} words; max 65"
            )
        # A long chain of sequence words is a strong signal that the model is merely
        # retelling the already-visible shot trail instead of interpreting it.
        sequence_hits = len(re.findall(r"\b(?:then|next|followed|after that|finally|before the|the next)\b", text, re.I))
        if sequence_hits >= 4:
            raise RuntimeError(
                f"Carnage commentary appears to narrate the shot sequence for {item.get('name')}; summarize the disaster instead"
            )

    for item in copy.get("players", []):
        body = (item.get("body") or "").strip()
        # Do not force every paragraph to hit a word target, but kill obvious stat-dump
        # monsters before they reach the site.
        words = re.findall(r"\b\w+[’'-]?\w*\b", body)
        if len(words) > 185:
            raise RuntimeError(
                f"Player body is too long / insufficiently selective for {item.get('name')}: {len(words)} words; max 185"
            )


write_recap.validate_copy = high_loft_validate


if __name__ == "__main__":
    write_recap.main()
