name: Temporary Tour 1534 player count trigger

on:
  push:
    paths:
      - 'tmp-tour1534-player-count-trigger.txt'

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo trigger-helper
